# @package _global_

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /base_mcmc
  - /dataset: colmap
  - /initialization: colmap
  - /render: 3dgut
  - _self_

# overwrite of default parameters
val_frequency: 999999 # never validate

initialization:
  use_observation_points: false
